### ISSUE TITLE
Try new AES128 constructor in pyca/cryptography

### ISSUE THREAD

**Issue by jelaiw** [jelaiw/serious-cryptography-book-examples#3]
## Notes
* See https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.algorithms.AES128.
* Upgrade from version 3.4.8 to 38.0.3.

**Comment by jelaiw** [comment]
Interestingly, we have upgraded to pyca/cryptography version 38.0.4 in `requirements.txt` for Binder, but we are still using the default devcontainer for Codespaces, which apparently is still at version 3.4.8.

```sh
$ cat requirements.txt 
cryptography==38.0.4
pycryptodome==3.15.0
bash_kernel==0.8.0
$ python --version
Python 3.10.4
```

**Comment by jelaiw** [comment]
```sh
$ cat requirements.txt 
cryptography==38.0.4
pycryptodome==3.15.0
bash_kernel==0.8.0
$ pip list | grep dome
pycryptodome             3.15.0
$ pip list | grep bash
bash_kernel              0.8.0
```

Note, we already have the other dependencies, so I guess we might as well just do `pip install -r requirements.txt` to bring pyca/cryptography up to version 38.0.4 (in our Codespaces VM).

**Comment by jelaiw** [comment]
Ok, looks like we are GTG.

```sh
--- SNIP ---

Installing collected packages: cryptography
  Attempting uninstall: cryptography
    Found existing installation: cryptography 3.4.8
    Uninstalling cryptography-3.4.8:
      Successfully uninstalled cryptography-3.4.8
Successfully installed cryptography-38.0.4
$ pip list | grep cryptography
cryptography             38.0.4
```

**Comment by jelaiw** [comment]
Confirm the new constructor raises an exception if we pass in a key where the size doesn't match the constructor.

```sh
$ python aes_block.py 
k = b'41009a75c2002e68d6567e6c2bc1b4fe'
Traceback (most recent call last):
  File "/workspaces/serious-cryptography-examples/Chapter_4_Block_Ciphers/aes_block.py", line 10, in <module>
    cipher = Cipher(algorithms.AES256(k), modes.ECB())
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 58, in __init__
    self.key = _verify_key_size(self, key)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 19, in _verify_key_size
    raise ValueError(
ValueError: Invalid key size (128) for AES.
```
